You reached the start of the range → Jan 12, 2025 5:07 PM

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 190, in __init__

  File "/opt/venv/lib/python3.11/site-packages/gunicorn/util.py", line 370, in import_app

    mod = importlib.import_module(self.SETTINGS_MODULE)

    mod = importlib.import_module(module)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/.nix-profile/lib/python3.11/importlib/__init__.py", line 126, in import_module

  File "/root/.nix-profile/lib/python3.11/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load

  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 940, in exec_module

  File "<frozen importlib._bootstrap_external>", line 940, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/app/Albino_Marks/settings.py", line 81, in <module>

  File "/app/Albino_Marks/wsgi.py", line 16, in <module>

    'default': dj_database_url.config(default=config('DATABASE_URL')  # Use a variável DATABASE_URL do ambiente Railway

    application = get_wsgi_application()

                                              ^^^^^^^^^^^^^^^^^^^^^^

                  ^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/decouple.py", line 248, in __call__

  File "/opt/venv/lib/python3.11/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application

    return self.config(*args, **kwargs)

    django.setup(set_prefix=False)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/django/__init__.py", line 19, in setup

    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)

  File "/opt/venv/lib/python3.11/site-packages/decouple.py", line 107, in __call__

                      ^^^^^^^^^^^^^^^^^^^^^^^

    return self.get(*args, **kwargs)

  File "/opt/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in __getattr__

    self._setup(name)

           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.11/site-packages/decouple.py", line 92, in get

    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))

decouple.UndefinedValueError: DATABASE_URL not found. Declare it as envvar or define a default value.

[2025-01-12 20:08:08 +0000] [4] [INFO] Worker exiting (pid: 4)

[2025-01-12 20:08:08 +0000] [1] [ERROR] Worker (pid:4) exited with code 3

[2025-01-12 20:08:08 +0000] [1] [ERROR] Shutting down: Master

[2025-01-12 20:08:08 +0000] [1] [ERROR] Reason: Worker failed to boot.